# Generated by Django 3.1.5 on 2021-02-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210208_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='shares',
        ),
    ]
